### PR TITLE
Update dbt_project.yml

### PR DESCRIPTION
**Pull request by jpetey75**
update version and change `source-paths` to new label `model-paths`

### CODE REVIEW

**Comment by jpetey75** [comment]
@rahilsondhi @MasterOdin some updates to the template so it works right out of the box in PopSQL without any warnings

**Review by MasterOdin — APPROVED** [review]
Changes look good, though I'd not change the `version` field as that's not really meant for us to version this repo, rather for a downstream user, and it'd be weird to start at a non-zero version.

**Comment by jpetey75** [comment]
Makes sense @MasterOdin i kept v1.0.0 for now. I don't have write access so can you merge if it looks good?

**Comment by MasterOdin** [comment]
@jpetey75 Merged this PR. I've also made a follow-up commit that updates the `data-paths` to `seed-paths` per changelog entry on https://docs.getdbt.com/reference/dbt_project.yml: 3f89af42f8fd93499ea0b64930ec8b8ef1117bf5

**Pull request merged**
